clean:
	cd ssh; make clean
	cd HadoopOverview; make clean
	cd HDFS; make clean
	cd MapReduce; make clean
	cd Hive; make clean
	cd Pig; make clean
	cd JavaAPI; make clean
	cd Streaming; make clean
	cd Yarn; make clean
	cd Hue; make clean
	rm -f *~
